{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "719c2411-dca9-4003-97a4-fd011ea1b56e",
   "metadata": {},
   "source": [
    "# Desafio 1 -  O Clássico FizzBuzz\n",
    "\n",
    "Escreva um programa que imprima os números de $1$ a $100$.\n",
    "\n",
    "Para múltiplos de 3, imprima Fizz em vez do número.\n",
    "\n",
    "Para múltiplos de 5, imprima Buzz em vez do número.\n",
    "\n",
    "Para números múltiplos de 3 e 5 ao mesmo tempo, imprima FizzBuzz.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ff3df503-31b6-4e43-975f-c67653c77d24",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "2\n",
      "Fizz\n",
      "4\n",
      "Buzz\n",
      "Fizz\n",
      "7\n",
      "8\n",
      "Fizz\n",
      "Buzz\n",
      "11\n",
      "Fizz\n",
      "13\n",
      "14\n",
      "FizzBuzz\n",
      "16\n",
      "17\n",
      "Fizz\n",
      "19\n",
      "Buzz\n",
      "Fizz\n",
      "22\n",
      "23\n",
      "Fizz\n",
      "Buzz\n",
      "26\n",
      "Fizz\n",
      "28\n",
      "29\n",
      "FizzBuzz\n",
      "31\n",
      "32\n",
      "Fizz\n",
      "34\n",
      "Buzz\n",
      "Fizz\n",
      "37\n",
      "38\n",
      "Fizz\n",
      "Buzz\n",
      "41\n",
      "Fizz\n",
      "43\n",
      "44\n",
      "FizzBuzz\n",
      "46\n",
      "47\n",
      "Fizz\n",
      "49\n",
      "Buzz\n",
      "Fizz\n",
      "52\n",
      "53\n",
      "Fizz\n",
      "Buzz\n",
      "56\n",
      "Fizz\n",
      "58\n",
      "59\n",
      "FizzBuzz\n",
      "61\n",
      "62\n",
      "Fizz\n",
      "64\n",
      "Buzz\n",
      "Fizz\n",
      "67\n",
      "68\n",
      "Fizz\n",
      "Buzz\n",
      "71\n",
      "Fizz\n",
      "73\n",
      "74\n",
      "FizzBuzz\n",
      "76\n",
      "77\n",
      "Fizz\n",
      "79\n",
      "Buzz\n",
      "Fizz\n",
      "82\n",
      "83\n",
      "Fizz\n",
      "Buzz\n",
      "86\n",
      "Fizz\n",
      "88\n",
      "89\n",
      "FizzBuzz\n",
      "91\n",
      "92\n",
      "Fizz\n",
      "94\n",
      "Buzz\n",
      "Fizz\n",
      "97\n",
      "98\n",
      "Fizz\n",
      "Buzz\n"
     ]
    }
   ],
   "source": [
    "# solução\n",
    "# primeiro defino minhas variáveis que são os múltiplos e os textos que vou imprimir\n",
    "x = 3\n",
    "y = 5\n",
    "f = \"Fizz\"\n",
    "b = \"Buzz\"\n",
    "fb= \"FizzBuzz\"\n",
    "# usei uma função de repetição para gerar os números, preferi usar o for aqui junto com a função range que gera o loop de 1 até 100. \n",
    "# a operador % deixa o resto da divisão, se ele for múltiplo o resto é 0\n",
    "for i in range(1,101):\n",
    "    #Depois usei o operar de condicional, if ,  para verificar se é divisível por 3 e 5  \n",
    "    if i%x ==0 and  i%y ==0: \n",
    "       print (fb)\n",
    "        # da pra fazer usando print(f,b), mas fica separado e além disso ao invés de usar \"and\" poderia só colocar um if e i%15\n",
    "    elif i%x ==0: \n",
    "        print (f)\n",
    "    elif i%y ==0: \n",
    "        print (b)\n",
    "    else :\n",
    "        print (i)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "212ea1cd-a8ad-49ca-a450-eee2fe5723b8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
